document.write('  <section id="portfolio" class="portfolio" data-ar-id="CuPvSi076z">');
document.write('            <div class="container" data-aos="fade-up" data-ar-id="O2doKYEU9F">');
document.write('');
document.write('                <div class="section-title" data-ar-id="ZgMgMcgqqD">');
document.write('                    <h2 data-ar-id="QbS8Qrnj1G">Our profit</h2>');
document.write('                    <p data-ar-id="dpa3N1e9uq">There is a small part of our free cryptor signals, you will find more screenshots in our community! We have everything honestly and with proof !</p>');
document.write('                </div>');
document.write('');
document.write('                <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200" data-ar-id="ppZpWdHC4Z">');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-app" data-ar-id="A55q2V28x7">');
document.write('                        <div class="portfolio-img" data-ar-id="z2QzNCKxOF">');
document.write('                            <img src="images/HYLaeKAyOu4uurQKtcpPGeqfRhfZYiiiXatdeWxO.jpg" class="img-fluid" alt="" data-ar-id="0ZVu3lRV4C">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="ViuFHEYuEn">');
document.write('                            <h4 data-ar-id="BnPdfeCIqn">FTM/USDT</h4>');
document.write('                            <p data-ar-id="ojx9wrJ3BM">SHORT</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-1.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 1" data-ar-id="Sl7mzaQVXj"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="prO8lI26rP"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-web" data-ar-id="TCsFxWN2M4">');
document.write('                        <div class="portfolio-img" data-ar-id="4H72FDfgIg">');
document.write('                            <img src="images/P3iYKUSb1yYkSPG8sh9sI6dzb2i1vwLZgqVm9jyw.jpg" class="img-fluid" alt="" data-ar-id="6lFlZCcxFq">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="JEv4LUGytU">');
document.write('                            <h4 data-ar-id="TpEPAlpj65">BTC/USDT</h4>');
document.write('                            <p data-ar-id="5LxcBAOPmZ">LONG</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-2.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 3" data-ar-id="355ap8aAdt"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="gL14FUdQRN"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-app" data-ar-id="nsFWJwxqBY">');
document.write('                        <div class="portfolio-img" data-ar-id="6RqSQHgwSG">');
document.write('                            <img src="images/1M0zd0MHrwI9duJFAy5KVvAyF3MwUyntOWtdARJB.jpg" class="img-fluid" alt="" data-ar-id="9c8e9von8B">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="LWhBqelMxt">');
document.write('                            <h4 data-ar-id="gnxeznsWWV">DYDX/USDT</h4>');
document.write('                            <p data-ar-id="p4iTnUosm0">SHORT</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-3.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 2" data-ar-id="uiWDeHTPy6"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="UcpNESZ7Zc"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-card" data-ar-id="Szfv1XHubt">');
document.write('                        <div class="portfolio-img" data-ar-id="W5j6KlreEf">');
document.write('                            <img src="images/tuOBF2CbPtpSj5SnjWbGLYGY2w2beiYWbokjZdrb.jpg" class="img-fluid" alt="" data-ar-id="Z2iMuDSkfo">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="3IRMM0tS7W">');
document.write('                            <h4 data-ar-id="NWUzsX6Nt7">CRV/USDT</h4>');
document.write('                            <p data-ar-id="cPEPxmPvBM">LONG</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-4.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Card 2" data-ar-id="p2CfRP8Lle"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="T4PyOj0Ap4"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-web" data-ar-id="IEgm6GtyRW">');
document.write('                        <div class="portfolio-img" data-ar-id="VMDYySZnQP">');
document.write('                            <img src="images/JtY8IBqj8mYFkogoFEda6TgYcMFBNfKwUhQwaqpx.jpg" class="img-fluid" alt="" data-ar-id="QWNw5YmXDq">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="e8bPnzl9Fo">');
document.write('                            <h4 data-ar-id="J1UACzaK7M">ETH/USDT</h4>');
document.write('                            <p data-ar-id="jDGnq07Nwy">SHORT</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-5.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 2" data-ar-id="nHoX0OKKFp"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="6EGsMUDnaU"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-app" data-ar-id="iDupCbonja">');
document.write('                        <div class="portfolio-img" data-ar-id="d4rq6KYBpg">');
document.write('                            <img src="images/HaLPxNdOsJ4qe2gYbTQUK1jz2CBteYB6HtnCb5qV.jpg" class="img-fluid" alt="" data-ar-id="cFLzyaDnwu">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="dbRfFdBM8b">');
document.write('                            <h4 data-ar-id="lAuDQCxIhV">APT/USDT</h4>');
document.write('                            <p data-ar-id="cWV2yJFJgY">LONG</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-6.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="App 3" data-ar-id="UV7KAiXzef"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="l8OmXsfMv8"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-card" data-ar-id="7bjHlSAbZm">');
document.write('                        <div class="portfolio-img" data-ar-id="ltvPlC6gaW">');
document.write('                            <img src="images/Gl1EnXumXFPx2nd6N5sX8GWD2PwJdHRid4bvc8AJ.jpg" class="img-fluid" alt="" data-ar-id="V2qkg8nIxf">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="C93OuOKbKx">');
document.write('                            <h4 data-ar-id="nY9xoLKM73">DOT/USDT</h4>');
document.write('                            <p data-ar-id="0HkoDsGYAg">LONG</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-7.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Card 1" data-ar-id="MA8Vi4XiCq"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="N2NgsgcCKh"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-card" data-ar-id="6R1afPWmn9">');
document.write('                        <div class="portfolio-img" data-ar-id="3P6qNrAWeI">');
document.write('                            <img src="images/4qeDU3M3UFQlI1iJpINz5VUKrKVS7XxezXYLCeCJ.jpg" class="img-fluid" alt="" data-ar-id="FQ0YDUM2ZZ">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="uOoBikDVAH">');
document.write('                            <h4 data-ar-id="ssWcvtcgpp">BTC/USDT</h4>');
document.write('                            <p data-ar-id="20CPFc3UXP">LONG</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-8.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Card 3" data-ar-id="GCpjtnlvo1"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="wrPRX0BhS6"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="col-lg-4 col-md-6 portfolio-item filter-web" data-ar-id="idsyG2g2Xb">');
document.write('                        <div class="portfolio-img" data-ar-id="ysiysc55a3">');
document.write('                            <img src="images/gyuJA4apvPyHwMGYLqFPNY8k2MJb3jwClMTiNX8O.JPG" class="img-fluid" alt="" data-ar-id="jXqRsIpmxz">');
document.write('                        </div>');
document.write('                        <div class="portfolio-info" data-ar-id="9U9oaQOEPc">');
document.write('                            <h4 data-ar-id="9nQ10FnC7g">ETH/USDT</h4>');
document.write('                            <p data-ar-id="owAddwBVTB">SHORT</p>');
document.write('                            <a href="assets/img/portfolio/portfolio-9.jpg" data-gall="portfolioGallery" class="venobox preview-link" title="Web 3" data-ar-id="CuQzigI0gK"></a>');
document.write('                            <a href="portfolio-details.html" class="details-link" title="More Details" data-ar-id="oahqjvs8tN"></a>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                </div>');
document.write('');
document.write('            </div>');
document.write('        </section>');
